# define our source to loook for gems
source "http://rubygems.org/"

# declare the sinatra dependency
gem "sinatra" 

# declare the selenium-webdriver dependency
gem "selenium-webdriver"

# declare the json dependency
gem "json"


# declare the mongo dependency
gem "mongo"
